### ISSUE TITLE
TODO: Create a database that contains the candidates table

### ISSUE THREAD

**Issue by crosenfrisk** [crosenfrisk/u-develop-it#1]
**User Story**

- [x]   * As a user, I can request a list of all potential candidates.

- [x]   * As a user, I can request a single candidate's information.

- [x]   * As a user, I want to delete a candidate.

- [x]   * As a user, I want to create a candidate.

**Comment by crosenfrisk** [comment]
Examples from lesson: 

* SELECT * FROM candidates;

* SELECT * FROM candidates WHERE id = 3;

* DELETE FROM candidates WHERE first_name = "Montague";

* INSERT INTO candidates (first_name, last_name, industry_connected)
VALUES ('Ronald', 'Firbank', 1);

**Comment by crosenfrisk** [comment]
- Connect to a MySQL database with a Node.js application.
- Execute SQL queries in Express.js routes using MySQL methods.
- Test the API endpoint using Insomnia and the browser.

**Comment by crosenfrisk** [comment]
- [ ]  * As a user, I can request a list of all potential candidates.
Done! 

db.query(`SELECT * FROM candidates`, (err, rows) => {
    console.log(rows);
});

**Comment by crosenfrisk** [comment]
- [ ] * As a user, I can request a single candidate's information.

db.query(`SELECT * FROM candidates WHERE id = 1`, (err, row) => {
    if (err) {
      console.log(err);
    }
    console.log(row);
  });

**Comment by crosenfrisk** [comment]
- [ ] * As a user, I want to delete a candidate.

db.query(`DELETE FROM candidates WHERE id = ?`, 1, (err, result) => {
    if (err) {
      console.log(err);
    }
    console.log(result);
  });

**Comment by crosenfrisk** [comment]
- [ ]  * As a user, I want to create a candidate.

const sql = `INSERT INTO candidates (id, first_name, last_name, industry_connected) 
              VALUES (?,?,?,?)`;
const params = [1, 'Ronald', 'Firbank', 1];

db.query(sql, params, (err, result) => {
  if (err) {
    console.log(err);
  }
  console.log(result);
});
